SMA_long = 1000
SMA_short = 50

BULL_rsi = 10
BULL_high = 80
BULL_low = 60
BULL_mod_high = 5
BULL_mod_low = -5

BEAR_rsi = 15
BEAR_high = 50
BEAR_low = 20
BEAR_mod_high = 15
BEAR_mod_low  = -5

ADX_adx = 3
ADX_high = 70
ADX_low = 50
